version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/transactions_db
      - REDIS_URL=redis://redis:6379/0
      - API_KEY=your_secret_api_key
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=transactions_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7

  celery_worker:
    build: .
    command: celery -A app.services.celery_worker worker --loglevel=info
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/transactions_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - db

volumes:
  postgres_data: